### ISSUE TITLE
Add Gitter

### ISSUE THREAD

**Issue by Jentsch** [scala-berlin/organisation#2]
We would like to have a platform for fast communication.

Gitter is a common that provides this service.

We want to have a chat under https://gitter.im/scala-berlin/scala-berlin

**Comment by Jentsch** [comment]
I tried to add channel in Gitter, but this new organisation doesn't show up

**Comment by markusjura** [comment]
Done.
scala-berlin: https://gitter.im/scala-berlin/scala-berlin
organisation (can be used to discuss things as organisers): https://gitter.im/scala-berlin/organisation
